### ISSUE TITLE
Error: Cannot apply to a multi user: Object "Cube_phys", Mesh "Cube.001", aborting

### ISSUE THREAD

**Issue by Idol11112222** [theanine3D/source-engine-collision-tools#1]
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\source_engine_collision_tools.py", line 313, in execute
    bpy.ops.object.transform_apply(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot apply to a multi user: Object "Cube_phys", Mesh "Cube.001", aborting

i tested on a default cube

**Comment by Idol11112222** [comment]
Update: I fixed the issue by adding a line with "bpy.ops.object.make_single_user(type='SELECTED_OBJECTS', object=True, obdata=True)" at position 312(before the transform was apply)

**Comment by theanine3D** [comment]
Thanks for pointing this out. Multi-user objects were definitely not a scenario I had considered or encountered yet in my own tests, so the code didn't account for it.

I just updated the code in the main branch so that the Generate Source Collision operator now forces the object to become single-user.
