### ISSUE TITLE
one issue remain its odd

### ISSUE THREAD

**Issue by demonelectro** [theanine3D/source-engine-collision-tools#10]
![image](https://github.com/user-attachments/assets/d952afbf-3ffc-4161-a0c5-3f2523f12ac2)
![image](https://github.com/user-attachments/assets/028049fb-44f4-48cf-9150-b62d226152da)
![image](https://github.com/user-attachments/assets/2f0f75fd-aa39-445a-9afd-aa83c5188bcd)
![image](https://github.com/user-attachments/assets/2d198e92-cf22-47d6-ab52-422d33042799)

**Comment by demonelectro** [comment]
new blend file with the issue : https://www.mediafire.com/file/z24zbyzjmvpj5x7/Castle_Gothique.blend/file

![image](https://github.com/user-attachments/assets/5e77dc4f-bde5-477c-912e-2d2379cf292a)

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/0e68218e-aea2-43a1-af3e-901e1b1e852b)
i selected what cause the issue of the physic is not accurate or not allow the player to go inside the tower

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/212d2b55-9242-4a24-acd3-ff4c9866feba)

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/815efb1f-571c-4b92-8eaf-52c60d11a68d)

**Comment by theanine3D** [comment]
This is not an issue with the addon. Your collision mesh simply has too many hulls. You're not supposed to have more than 32 in a single collision mesh. If you do, the compiler starts merging them together to force the amount to still be 32 or under. When I press Force Convex to count the amount of hulls, I get an enormous amount - over 400 hulls.

![image](https://github.com/user-attachments/assets/ef59b8ba-5449-473b-bd82-4068df732276)

You will need to either 1) split this up using the Split Up Collision Mesh button. This will divide it into many 32-hull pieces, which then can be added to the VMF automatically with the Update VMF feature.

or 2) clean up the mesh manually, merge hulls together in Edit Mode where appropriate, until you're able to manually get this down to only a much smaller amount of hulls. You may still need to export several different collision meshes instead of just one big one though.

(There is a third, but not recommended, option: the $[maxconvexpieces ](https://developer.valvesoftware.com/wiki/Costly_collision_model)line in the QC file will let you bypass the 32-hull limit. The problem with this method is that it causes the map to lag horribly in online multiplayer games. If your map is just single player then you can do this as a last resort, if the other 2 options seem like too much work.)

**Comment by demonelectro** [comment]
nothing work i will try to divide and reduce as i can or we will cheat or do something else instead

**Comment by demonelectro** [comment]
okay update everything work like you said its hull limitation i reduced the decimate ratio its fixed all
