### ISSUE TITLE
Error: BlockingIOError: [Errno 11] write could not complete without blocking

### ISSUE THREAD

**Issue by some-username-here1** [theanine3D/source-engine-collision-tools#2]
Occurs the first few times after executing "Merge Adjacent Similars", but I have no idea what's causing this error as it ends up going away after hitting the button a couple of more times, like 4 or so. Forgot to mention, but blender version is `3.5.1`.
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/34193156/a5f80310-b01c-4c94-9d9e-b08f0fb2a501)

**Comment by theanine3D** [comment]
I did some digging, and it looks like this is most likely caused by the console printing too much text at a time. By default, I had it print out verbosely what it was doing, but this might be causing problems. 

Copy the updated code below to your locally installed addon .py file, or just reinstall the new one. Alternatively, comment out the lines 852 and 853 in the Python file you already have installed (by adding a # at the start of both lines). Let me know if this doesn't fix it.
https://raw.githubusercontent.com/theanine3D/source-engine-collision-tools/main/source_engine_collision_tools.py
