### ISSUE TITLE
Split Up Collision Mesh Freezes Up Blender

### ISSUE THREAD

**Issue by CFalcon075** [theanine3D/source-engine-collision-tools#3]
Hi, I just started using this plugin for Blender. I am a complete newbie at this but I did in fact see the video, I was trying to split the collision mesh and I downloaded the latest version of the plugin.

I am using a model that is a very costly model that was from a website that I got from for free. I wanted to port it into Garry's Mod. The generate collision mesh did in fact work (thought I had to tell you that). I see that the model is a very costly model that when tried to compile with Crowbar it complains a lot, saying that it is a costly model and the warning for the 2D-geometry for the model is less than 0.500 thickness, that type of error.

So when I tried to see if the split up collision mesh would work so that way it would not be so costly, it freezes up Blender as a whole and I've waited for about a good hour and thirty minutes or so, but in the video for your map that you have on there it totally goes by really fast!

I wanted to desperately know what the problem is, and I'll attach an image down below of the model that I have, I am still a beginner at all of this like reiterated. 

![Screenshot 2023-10-29 151127](https://github.com/theanine3D/source-engine-collision-tools/assets/38923178/6990aeee-72cb-4dc2-877b-fe44c445eafa)

So as you see in this screenshot that's the model, and here is a GIF file of when the program literally freezes up. 

[https://imgur.com/a/BepoXv2](url)

I am still seeing it being unresponsive (Blender), and I simply do not know how to fix this. If you can try to fix this issue on the plugin, very good! If you also found a better way how to fix the issue on my end without having to fix the plugin, again very good!

Please let me know what you think, thanks!

**Comment by theanine3D** [comment]
This Nvidia graphics card model is just going to be a grabbable prop in Gmod, right? Because if so, I think maybe you have misunderstood what the "Split Up Collision Mesh" feature is for. Split Up Collision is intended for use with the collision mesh for a whole scene. You should never, ever need that feature for a single (and small) prop, like a graphics card. If you're finding yourself needing it for a single/small prop, it means you've made a collision mesh that is way too overly complex. The fact that Crowbar is complaining corroborates this.

For a small prop like this, particularly if it has no moving/animated parts, you're much better off just creating a single cube as a collision mesh. Resize the cube so it fits the shape of the graphics card. Press Ctrl + A and choose "Rotation and Scale" to finalize the new size, and make sure its origin point is the same as the original model. 

If a resized cube doesn't provide enough detail in the physics mesh for your needs, you can also try the "Generate Fractured Collision" feature. It can generate something more detailed than a box shape, but still very low on hull count, so Crowbar will not complain (and again, you will not need Split Up Collision at all).

**Comment by CFalcon075** [comment]
> This Nvidia graphics card model is just going to be a grabbable prop in Gmod, right? Because if so, I think maybe you have misunderstood what the "Split Up Collision Mesh" feature is for. Split Up Collision is intended for use with the collision mesh for a whole scene. You should never, ever need that feature for a single (and small) prop, like a graphics card. If you're finding yourself needing it for a single/small prop, it means you've made a collision mesh that is way too overly complex. The fact that Crowbar is complaining corroborates this.
> 
> For a small prop like this, particularly if it has no moving/animated parts, you're much better off just creating a single cube as a collision mesh. Resize the cube so it fits the shape of the graphics card. Press Ctrl + A and choose "Rotation and Scale" to finalize the new size, and make sure its origin point is the same as the original model.
> 
> If a resized cube doesn't provide enough detail in the physics mesh for your needs, you can also try the "Generate Fractured Collision" feature. It can generate something more detailed than a box shape, but still very low on hull count, so Crowbar will not complain (and again, you will not need Split Up Collision at all).

Wow, that enlightened me since I thought it was the program doing something silly! I am so glad it's just me since I wouldn't have ever guessed what went wrong, I supposed that the split up collision would make it to where the convex hulls would be 32 
 in order for the collision mesh to be cheap for the prop or something like that. I really don't know how all of this works and trust me I'm a complete beginner at this, I should read more on the Valve Developer Wiki but I sometimes feel like I can solve it myself.

It was a pleasure for you to explain to me what this does! Thank you so so much!!

P.S. Yes you are right, it's a grabbable prop! :)
