### ISSUE TITLE
Issues converting model to collision.

### ISSUE THREAD

**Issue by timonenluca** [theanine3D/source-engine-collision-tools#4]
When converting the x & z values are off  , also seems seperate models even turn in full convex box on recommended settings instead of following the models shape.

[Github_issue_model.zip](https://github.com/theanine3D/source-engine-collision-tools/files/13619421/Github_issue_model.zip)

**Comment by theanine3D** [comment]
I had no problem generating collision for almost everything in this file.
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/5de5212a-d986-4038-8bef-ec6673cfd721)

The only thing that gave me an issue was the floor. With the Recommended Settings, it generates the collision far above the original ground, and the resulting collision is too thin (which will likely cause Source Engine's model compiler to complain)
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/a74e7866-da88-4db7-9da0-05319a2191e1)

This has a simple workaround. Simply extrude the original ground mesh downward first, so that it has some 3D depth. (The Solidify modifier can do this too, just press Apply on it after you add it). As long as the ground has some 3D depth (instead of being just a flat plane), the collision is generated with only one minor issue: it's still being placed way above the ground. You can simply move it downward afterward.

![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/0d77c2d3-e3fe-4782-9298-d022782df6ac)

It seems that the addon just doesn't like 100% flat/paperthin objects. I'll look into seeing if there's a way to address that.

**Comment by theanine3D** [comment]
I just did another test and had no issue generating collision for the entire scene all at once:
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/b3398408-1c9e-4966-974d-b821758a9348)

How I did it: I joined all of the meshes together into one single object first. Then I generated the collision. This time, the ground collision was generated just fine, along with everything else.
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/6d65097c-c7be-44a6-bdda-95b8dc02cf3c)

So it seems that it CAN handle paper-thin meshes, as long as they're part of another larger object.

Try selecting all meshes in your scene and press Ctrl + J to join them into one object. Then press the Recommended Settings button, and press Generate Collision Mesh button. You should have no problems.

**Comment by timonenluca** [comment]
What blender version are you using if i may ask? I still have the bug unfortunately. I am on 3.3.0

**Comment by theanine3D** [comment]
I took those screenshots in Blender 3.6.5,

But I just downloaded 3.3 and tested it there too. It worked fine. This screenshot below is from Blender 3.3. No issues, as long as the meshes were all joined together first.
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/b095b1ff-2b15-4c44-80a4-fdfcf1feb196)

**Comment by timonenluca** [comment]
I unfortunately still have the same issue :(.

Here is a video i made , showcasing the problem while using the tool.
https://youtu.be/Iej2IHBV-R8

**Comment by theanine3D** [comment]
I was able to recreate the issue by importing the FBX, instead of using your .blend file.

It seems to be related to the scale/rotation after you join the objects together. After pressing Ctrl + J, press **Ctrl + A** and then choose "**Rotation and Scale**"

This fixed the issue for me. So just going forward, make sure you apply the rotation and scale before generating, and you should have no problem. I'll see if I can add some code to the addon that does this automatically.

P.S. It looks like, in the .blend you provided, the rotation and scale was already applied, and that's why it worked fine for me. But importing the FBX from scratch resulted in a model that still needed the rotation and scale applied. You can see this yourself if you import the FBX and then press Alt + R and Alt + S to reset the rotation/scale. It will rotate the object upward like in your YouTube video.
