### ISSUE TITLE
Confused about using this.

### ISSUE THREAD

**Issue by AwertaDreams** [theanine3D/source-engine-collision-tools#5]
Hello! I'm new to blender and im really confused by this plugin.
I turned my text into a mesh. Then, when i used your plugin - this weird collision comes out of it: 
![y](https://github.com/theanine3D/source-engine-collision-tools/assets/134288412/5177fa87-cb02-4cb1-b6d4-1cb81c8d076a)
![x](https://github.com/theanine3D/source-engine-collision-tools/assets/134288412/2e9c3a21-9eba-4d1d-97cf-6940aa1fd16c)
Then, in game it looks like this: 
![ha](https://github.com/theanine3D/source-engine-collision-tools/assets/134288412/12b83c38-cf94-4e2e-a28c-f2fa15d7589d)
And i get a lot of warnings from crowbar, saying this:
`WARNING: Model has 2-dimensional geometry (less than 0.500 inches thick on any axis)!!!`

Blender version is 4.0

**Comment by theanine3D** [comment]
The addon currently sometimes struggles with 100% flat meshes. You can prevent issues by making sure the mesh has at least a tiny bit of 3D depth.

If the text mesh is completely flat, add a Solidify modifer to it first and then apply the modifier. Then press Ctrl + A and choose Rotation & Scale. Then try generating the collision again.

Please try the above and let me know if it worked for you.

**Comment by AwertaDreams** [comment]
![obraz](https://github.com/theanine3D/source-engine-collision-tools/assets/134288412/c73804af-0340-49ff-8a0c-8f5fe03a1d57)
![obraz](https://github.com/theanine3D/source-engine-collision-tools/assets/134288412/32a6b774-383a-4e59-bc73-b862826230b8)
![obraz](https://github.com/theanine3D/source-engine-collision-tools/assets/134288412/018d665f-8864-4382-8cdb-08db948c7fb8)

Do I need to use any of the other settings? Like Splitting up the collision mesh and merging adjacent similliars?

Edit: i did everything you told me, and I still get the same warning. Heres the blend file alongside with the qc models, files, and compile log: 
[Weird issue.zip](https://github.com/theanine3D/source-engine-collision-tools/files/14360665/Weird.issue.zip)

**Comment by theanine3D** [comment]
You didn't apply the Solidify modifier like I instructed. I opened your .blend file and the two Solidify modifiers are still there (you shouldn't need two of them, by the way - having two will actually likely cause problems). You need to apply one Solidify modifier before generating the collision, otherwise the collision will be generated based on the original flat geometry.

![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/75e68773-db03-43bc-9682-e5352ee94d70)

Delete the collision mesh and start from scratch. Put the Solidify modifier on the **original** text mesh, not the generated collision. Then apply that modifier. **Then** generate the collision. In that specific order.
